<?xml version="1.0" encoding="UTF-8"?>
<testng-results ignored="0" total="1" passed="0" failed="1" skipped="0">
  <reporter-output>
  </reporter-output>
  <suite started-at="2022-03-10T11:01:02 CST" name="Default suite" finished-at="2022-03-10T11:01:07 CST" duration-ms="4881">
    <groups>
    </groups>
    <test started-at="2022-03-10T11:01:02 CST" name="Default test" finished-at="2022-03-10T11:01:07 CST" duration-ms="4881">
      <class name="OrangeHRMLogin.OrangeHRMTest1">
        <test-method is-config="true" signature="setup()[pri:0, instance:OrangeHRMLogin.OrangeHRMTest1@31e5415e]" started-at="2022-03-10T11:01:02 CST" name="setup" finished-at="2022-03-10T11:01:07 CST" duration-ms="4830" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setup -->
        <test-method signature="loginTest(java.lang.String, java.lang.String, java.lang.String)[pri:0, instance:OrangeHRMLogin.OrangeHRMTest1@31e5415e]" started-at="2022-03-10T11:01:07 CST" name="loginTest" data-provider="LoginData" finished-at="2022-03-10T11:01:07 CST" duration-ms="0" status="FAIL">
          <exception class="org.testng.TestNGException">
            <message>
              <![CDATA[
Method public void OrangeHRMLogin.OrangeHRMTest1.loginTest(java.lang.String,java.lang.String,java.lang.String) requires a @DataProvider named : LoginData]]>
            </message>
            <full-stacktrace>
              <![CDATA[org.testng.TestNGException: 
Method public void OrangeHRMLogin.OrangeHRMTest1.loginTest(java.lang.String,java.lang.String,java.lang.String) requires a @DataProvider named : LoginData
at org.testng.internal.Parameters.findDataProvider(Parameters.java:563)
at org.testng.internal.Parameters.handleParameters(Parameters.java:776)
at org.testng.internal.Parameters.handleParameters(Parameters.java:744)
at org.testng.internal.ParameterHandler.handleParameters(ParameterHandler.java:59)
at org.testng.internal.ParameterHandler.createParameters(ParameterHandler.java:38)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:783)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:766)
at org.testng.TestRunner.run(TestRunner.java:587)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:384)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:378)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:337)
at org.testng.SuiteRunner.run(SuiteRunner.java:286)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1187)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1109)
at org.testng.TestNG.runSuites(TestNG.java:1039)
at org.testng.TestNG.run(TestNG.java:1007)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- org.testng.TestNGException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- loginTest -->
        <test-method is-config="true" signature="tearDown()[pri:0, instance:OrangeHRMLogin.OrangeHRMTest1@31e5415e]" started-at="2022-03-10T11:01:07 CST" name="tearDown" finished-at="2022-03-10T11:01:07 CST" duration-ms="0" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
      </class> <!-- OrangeHRMLogin.OrangeHRMTest1 -->
    </test> <!-- Default test -->
  </suite> <!-- Default suite -->
</testng-results>
